[package]
name = "dberd"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.4.1", features = ["auto-color"] }
chumsky = "0.9.3"
clap = { version = "4.5.4", features = ["derive"] }
